local backup_SH_UTILS_DRY_RUN
local backup_SH_UTILS_ERRORS
backup_SH_UTILS_DRY_RUN=$SH_UTILS_DRY_RUN
backup_SH_UTILS_ERRORS=$SH_UTILS_ERRORS
SH_UTILS_DRY_RUN=${SH_UTILS_DRY_RUN:-"false"}
SH_UTILS_ERRORS=0
